# Generated by Django 5.1 on 2024-08-31 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_album_is_public_photo_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='like_users',
            field=models.ManyToManyField(related_name='like_albums', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
