# Generated by Django 5.1 on 2024-08-31 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_album_like_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like_users',
        ),
        migrations.AddField(
            model_name='album',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_albums', to=settings.AUTH_USER_MODEL, verbose_name='Favorite Users'),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_photos', to=settings.AUTH_USER_MODEL, verbose_name='Favorite Users'),
        ),
    ]
