# Generated by Django 5.1 on 2024-08-31 12:11

import uuid
from django.db import migrations, models

def populate_unique_tokens(apps, schema_editor):
    Photo = apps.get_model('webapp', 'Photo')
    for photo in Photo.objects.all():
        if photo.token is None:
            unique_token_found = False
            while not unique_token_found:
                token = uuid.uuid4()
                if not Photo.objects.filter(token=token).exists():
                    photo.token = token
                    photo.save(update_fields=['token'])
                    unique_token_found = True

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_album_like_users_remove_photo_like_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.RunPython(populate_unique_tokens),
    ]
